apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: menu-service
  template:
    metadata:
      labels:
        app: menu-service
    spec:
      containers:
      - name: app
        image: menu-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: REDIS_HOST
          value: "redis-service"
      - name: queue-worker
        image: menu-service:latest
        command: ["php", "artisan", "queue:work"]